/**
 * @file sentiment.h
 * @brief Lightweight keyword-based sentiment classifier.
 *
 * Scores user input on a scale from -10 (very negative) to +10 (very positive)
 * and classifies it into a human-readable label.  The score influences
 * the tone of responses generated by the NLP engine.
 */
#ifndef SENTIMENT_H
#define SENTIMENT_H

/** Sentiment score range. */
#define SENTIMENT_MIN -10
#define SENTIMENT_MAX  10

/**
 * @brief Analyse the sentiment of a tokenised input string.
 *
 * Scans for positive and negative keywords; each hit adds or subtracts 1.
 * Intensifiers ("very", "extremely") double the weight of the next keyword.
 *
 * @param input Raw, lower-cased input string.
 * @return Integer score in [SENTIMENT_MIN, SENTIMENT_MAX].
 */
int sentiment_score(const char *input);

/**
 * @brief Map a numeric score to a human-readable label.
 * @param score Score from sentiment_score().
 * @return One of "very positive", "positive", "neutral",
 *         "negative", "very negative".
 */
const char *sentiment_label(int score);

/**
 * @brief Map a sentiment score to an emoji-like ASCII indicator.
 * @param score Score from sentiment_score().
 * @return Short ASCII string e.g. "(^_^)", "(._.)".
 */
const char *sentiment_emoji(int score);

#endif /* SENTIMENT_H */
